#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::mysql;
use Mojo::Pg;

helper mysql => sub {
    state $pg => Mojo::mysql->new('mysql://root:root@localhost/testdb');
};

helper pg => sub {
    state $pg => Mojo::Pg->new('postgresql://root:root@localhost/testdb');
};

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
    shift->render(template => 'index');
};

get '/hi' => sub {
    shift->render(text => "Hello world!");
};

get '/mysql' => sub {
    my $c  = shift;
    my $db = $c->mysql->db;
    $c->render(json => $db->query('SELECT VERSION()')->hash);
};

get '/pg' => sub {
    my $c  = shift;
    my $db = $c->pg->db;
    $c->render(json => $db->query('SELECT version()')->hash);
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>
To learn more, you can browse through the documentation
<%= link_to 'here' => '/perldoc' %>.

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
